import imgApi from 'enl-api/images/photos';
const productData = [
  {
    id: '1',
    name: 'university of lahor',
    thumbnail: imgApi[21],
    desc: 'Curabitur egestas consequat lorem, vel fermentum augue porta id.',
    rating: 4,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '2',
    name: 'University of engineering Peshawar',
    thumbnail: imgApi[22],
    desc: 'Maecenas nisl libero, tincidunt id odio id, feugiat vulputate quam.',
    rating: 0,
    price: 15,
    prevPrice: 150,
    discount: '90%',
    soldout: false,
  },
  {
    id: '3',
    name: 'Fusce placerat enim et odio molestie sagittis',
    thumbnail: imgApi[23],
    desc: 'Duis tristique metus magna, lobortis aliquam risus euismod sit amet',
    rating: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '4',
    name: 'Pellentesque ac bibendum tortor',
    thumbnail: imgApi[24],
    desc: 'Nam posuere accumsan porta',
    rating: 2,
    price: 80,
    prevPrice: 100,
    discount: '20%',
    soldout: false,
  },
  {
    id: '5',
    name: 'Abbottabad University of Science and Technology',
    thumbnail: imgApi[25],
    desc: 'Aenean sit amet magna vel magna fringilla fermentum',
    rating: 5,
    price: 50,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '6',
    name: 'Bachelor of Arts in Business Communication (BA)',
    thumbnail: imgApi[26],
    desc: 'The Bachelor of Arts in Business Communication program will develop your core skills in writing and research and equip you with an understanding of business communication.',
    rating: 4,
    price: 75,
    prevPrice: 100,
    discount: '25%',
    soldout: false,
  },
  {
    id: '7',
    name: 'Bachelor of Arts in Business Communication(BA)',
    thumbnail: imgApi[27],
    desc: 'The Master of Business Administration program prepares you to tackle challenging situations and drive the success of your organization through intelligent decision-making.',
    rating: 5,
    price: 20,
    prevPrice: 16,
    discount: '20%',
    soldout: false,
  },
  {
    id: '8',
    name: 'Bachelor of Commerce (BCom)',
    thumbnail: imgApi[28],
    desc: 'he Bachelor of Commerce program prepares you for a successful career in business or management, where you will contribute constructively to a global economy.',
    rating: 1,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '9',
    name: 'Associate of Arts (AA)',
    thumbnail: imgApi[29],
    desc: 'The Associate of Arts program is an interdisciplinary set of courses that cultivate core skills in writing, communication, research and team performance.',
    rating: 4,
    price: 50,
    prevPrice: 100,
    discount: '50%',
    soldout: false,
  },
  {
    id: '10',
    name: 'Associate of Arts (AA)',
    thumbnail: imgApi[30],
    desc: 'Integer id orci sed ante tincidunt tincidunt sit amet sed libero.',
    rating: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '11',
    name: 'Cras convallis lacus orc',
    thumbnail: imgApi[37],
    desc: 'The Associate of Arts program is an interdisciplinary set of courses that cultivate core skills in writing, communication, research and team performance.',
    rating: 4,
    price: 66,
    prevPrice: 200,
    discount: '67%',
    soldout: false,
  },
];

export default productData;
