export const SEARCH_UNIVERSITY_REQUEST = "SEARCH_UNIVERSITY_REQUEST"
export const SEARCH_UNIVERSITY_SUCCESS = "SEARCH_UNIVERSITY_SUCCESS"
export const SEARCH_UNIVERSITY_FAIL = "SEARCH_UNIVERSITY_FAIL"

export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST"
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS"

export const SEND_STUDENT_INFO_REQUEST = "SEND_STUDENT_INFO_REQUEST"
export const SEND_STUDENT_INFO_SUCCESS = "SEND_STUDENT_INFO_SUCCESS"
export const SEND_STUDENT_INFO_FAIL = "SEND_STUDENT_INFO_FAIL"




