export const SEARCH_UNIVERSITY_REQUEST = "SEARCH_UNIVERSITY_REQUEST"
export const SEARCH_UNIVERSITY_SUCCESS = "SEARCH_UNIVERSITY_SUCCESS"
export const SEARCH_UNIVERSITY_FAIL = "SEARCH_UNIVERSITY_FAIL"


